/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Registration = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Float64,
  'height' : IDL.Float64,
  'dateOfBirth' : IDL.Text,
  'bust' : IDL.Float64,
  'hips' : IDL.Float64,
  'bioPlatformStatement' : IDL.Text,
  'fullName' : IDL.Text,
  'talentSkills' : IDL.Text,
  'fullBodyPhotoBlob' : IDL.Opt(ExternalBlob),
  'address' : IDL.Text,
  'occupationOrSchool' : IDL.Text,
  'timestamp' : IDL.Int,
  'emergencyContactPhone' : IDL.Text,
  'previousPageantExperience' : IDL.Text,
  'contactNumber' : IDL.Text,
  'emergencyContactName' : IDL.Text,
  'headshotBlob' : IDL.Opt(ExternalBlob),
  'waist' : IDL.Float64,
  'hobbiesInterests' : IDL.Text,
  'educationLevel' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const RegistrationId = IDL.Nat;

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getAllRegistrationsSortedByTimestamp' : IDL.Func(
      [],
      [IDL.Vec(Registration)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRegistration' : IDL.Func([RegistrationId], [Registration], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRegistration' : IDL.Func([Registration], [RegistrationId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Registration = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Float64,
    'height' : IDL.Float64,
    'dateOfBirth' : IDL.Text,
    'bust' : IDL.Float64,
    'hips' : IDL.Float64,
    'bioPlatformStatement' : IDL.Text,
    'fullName' : IDL.Text,
    'talentSkills' : IDL.Text,
    'fullBodyPhotoBlob' : IDL.Opt(ExternalBlob),
    'address' : IDL.Text,
    'occupationOrSchool' : IDL.Text,
    'timestamp' : IDL.Int,
    'emergencyContactPhone' : IDL.Text,
    'previousPageantExperience' : IDL.Text,
    'contactNumber' : IDL.Text,
    'emergencyContactName' : IDL.Text,
    'headshotBlob' : IDL.Opt(ExternalBlob),
    'waist' : IDL.Float64,
    'hobbiesInterests' : IDL.Text,
    'educationLevel' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const RegistrationId = IDL.Nat;
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getAllRegistrationsSortedByTimestamp' : IDL.Func(
        [],
        [IDL.Vec(Registration)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRegistration' : IDL.Func([RegistrationId], [Registration], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRegistration' : IDL.Func([Registration], [RegistrationId], []),
  });
};

export const init = ({ IDL }) => { return []; };